---
version: '3.8'
services:
  minecraft:
    image: server:latest
    container_name: hispanozuela-server
    ports:
      - "25565:25565"
    volumes:
      - ./server:/server
      - ./backups:/backups
    restart: always
    stdin_open: true
    tty: true
...